### ISSUE TITLE
Guidance regarding generated *.dll?

### ISSUE THREAD

**Issue by LegendaryB** [itaymigdal/Nimbo-C2#1]
Hey,

any guidance to use the generated *.dll which is the output of the build dll command?

Simple test scenario was:
Spawned notepad process and injected via LoadLibrary injector. The file is loaded by the process. Just validated it via Process Explorer. But no new agent shows up. 

Kind Regards

**Comment by itaymigdal** [comment]
Sure.
When you simply inject a DLL into a process, only the code in Dllmain->DLL_ATTACH_PROCESS is executed (which by the way is limited by the things it can do). The default Dll export name in Nimbo is DllRegisterServer (configurable by the config file).
Hence I the ways the execute the Dll:
1. `Regsvr32.exe na.dll`
2. `Rundll32.exe na.dll,DllRegisterServer`
3. Load it into the process as you did and then call this function.
Tell me how it goes.

Greetings :)
Itay

**Comment by LegendaryB** [comment]
Hey @itaymigdal,

it works as expected. Just tested it with rundll32 na.dll,DllRegisterServer
Will modify my injector to call the export after injection.

Thanks :)

**Comment by itaymigdal** [comment]
Glad to hear :)
Feel free to open more issues

**Comment by JitBox** [comment]
Hey all, @itaymigdal , I am also curious on this. I am able to execute this DLL by running rundll32 or regsvr32, but is there any way to have this DLL be executed when it is loaded into a process (like DLL sideloading)? 

I am doing an engagemetn where I need to do a COM object hijack and I can get a binary to load the dll, just wont execute unless I manually type rundll32 command or regsvr

**Comment by itaymigdal** [comment]
Hey @JitBox ,
From [MSDN](https://learn.microsoft.com/en-us/windows/win32/dlls/dllmain) :
`The entry-point function should perform only simple initialization or termination tasks. It must not call the LoadLibrary or LoadLibraryEx function (or a function that calls these functions), because this may create dependency loops in the DLL load order. This can result in a DLL being used before the system has executed its initialization code. Similarly, the entry-point function must not call the FreeLibrary function (or a function that calls FreeLibrary) during process termination, because this can result in a DLL being used after the system has executed its termination code.`

Thus

**Comment by LegendaryB** [comment]
Hey @itaymigdal,

sorry to reopen this ticket but was coming back and read your responses regarding the full C2 functionality in DllMain. 
What about creating a new Thread in DllMain like this:
```
switch(fdwReason) {
        case DLL_PROCESS_ATTACH:
            DisableThreadLibraryCalls(hinstDll);
            CreateThread(nullptr, 0, OnDllAttach, hinstDll, 0, nullptr);
            return TRUE;
```

 It's a common thing in used in game hacking for CS:GO for example. Maybe it could be an extra option when building a dll?

**Comment by itaymigdal** [comment]
Not planning to implement, sorry. If you think you can implement this and it'll work good, edit dll.nim in a new PR and I'll test it and maybe merge. 🙂
Also, if you have a relevant article on this topic, please share.

**Comment by itaymigdal** [comment]
ChatGPT on that:
Yes, you can create a new thread within DllMain's process attach. However, it's generally not considered a best practice to do so. DllMain is called with the loader lock held, and creating threads or performing lengthy operations within DllMain can lead to deadlocks and other issues, as it can interfere with the loader lock.

It's recommended to keep DllMain as simple and efficient as possible, primarily for initializing data structures and not for creating threads. If you need to perform more complex operations, consider using another initialization mechanism after your DLL has been loaded.

**Comment by LegendaryB** [comment]
Hey @itaymigdal, thanks for the fast response! 

Maybe I will give it a try. Will need to build up a Nim development environment first. Maybe on the weekend. ChatGPT is right, it's not best best practice but as long as you are not trying to synchronize threads or create objects with thread affinity it should work fine. Also I thinkt that CreateThread can be called without dependency problems because kernel32 and ntdll are always mapped first into the process.

But thats just theory, will really need to give it a try I guess

**Comment by itaymigdal** [comment]
Note that another limitation is that Nim threads work different than C/C++ , It has a garbage collector and threads need to be GC safe and stuff, it's more complicated. 
Feel free to DM me to keep discuss on this.

**Comment by LegendaryB** [comment]
Hey @itaymigdal,

do you have another way of contact maybe discord? Can write you a mail if you don't want to post it here in public. As I said before the weekend I will not be able to try it

**Comment by itaymigdal** [comment]
Look at my Github profile

**Comment by itaymigdal** [comment]
Did you use the provided docker image as explained in the readme (second method)?
