### ISSUE TITLE
Prompt me that nimprotect is missing?

### ISSUE THREAD

**Issue by bobmaifz1** [itaymigdal/Nimbo-C2#14]
so what should i do？

`Nimbo-C2 > build exe -o /root/ -v
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
....................................................................
/root/Nimbo-C2-3.1.0/Nimbo-C2/agent/config.nim(2, 8) Error: cannot open file: nimprotect
[-] ERROR: Could not compile
`

**Comment by bobmaifz1** [comment]
In addition, I think the modules required by python can be placed in txt for easy installation.

**Comment by itaymigdal** [comment]
Do you run this within the Docker image?

**Comment by bobmaifz1** [comment]
> Do you run this within the Docker image?

No!
Does it have to be run in docker? I thought docker was optional.

**Comment by itaymigdal** [comment]
Yes, it has to be run inside the provided docker image, as I wrote in the installation topic under the readme.
The project includes many software components and specific version to ensure it'll all play smoothly.

**Comment by bobmaifz1** [comment]
Thanks! Thanks for the project, it's really nice. but not suitable for me

**Comment by itaymigdal** [comment]
Thanks, appreciate it. Good luck 🙂
