### ISSUE TITLE
help the beginner please)

### ISSUE THREAD

**Issue by sigasiga123** [itaymigdal/Nimbo-C2#3]
in the process of learning, I came across your agent and decided to study, try to install it and work (I'm new to all this).
in the process of creating a payload, I have errors:
Nimbo-C2 > build exe -x
[-] ERROR: Could not compile
Nimbo-C2 > build dll -x
[-] ERROR: Could not compile
[-] ERROR: Could not UPX the agent

I'm sorry for the stupid question, but I'm a little stumped.)
I work on kali linux.

**Comment by itaymigdal** [comment]
As I wrote in the readme, you have to use it as a docker container. It wont work otherwise. Please refer to the installation in the readme..
