### ISSUE TITLE
Encrypted Communication

### ISSUE THREAD

**Issue by TaxMachine** [itaymigdal/Nimbo-C2#4]
its not an issue but could be an issue in the future, we have the same problem. Communications between client and server should be asymetric encryption like RSA but the problem is, from what i've tried, I didnt found a way to do so. Though, I know there's RSA encrypt and decrypt functions in the openssl module.

I'll let you know if i find out how but if you could search with me that would be awesome.

Best regards, Tax

**Comment by itaymigdal** [comment]
Hey my friend. Not going to implement soon, but if you manage to do it, id love to see 🙂
